name: Build RPK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build RPK
        run: npm run build

      - name: Show RPK files
        run: |
          echo "Searching for RPK..."
          find . -type f -name "*.rpk" -print

      - name: Upload RPK
        uses: actions/upload-artifact@v4
        with:
          name: calculator-rpk
          path: |
            dist/*.rpk
            dist/**/*.rpk
